# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 15:24
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0005_auto_20170714_1414'),
        ('events', '0002_eventdetailpage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventdetailpage',
            old_name='datetime',
            new_name='event_time',
        ),
        migrations.AddField(
            model_name='eventdetailpage',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventdetailpage',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0, 3600)),
        ),
        migrations.AddField(
            model_name='eventdetailpage',
            name='event_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.Event'),
        ),
    ]
